#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: da8b975
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : kuserfeedback
Version  : 1.3.0
Release  : 4
URL      : https://download.kde.org/stable/kuserfeedback/kuserfeedback-1.3.0.tar.xz
Source0  : https://download.kde.org/stable/kuserfeedback/kuserfeedback-1.3.0.tar.xz
Source1  : https://download.kde.org/stable/kuserfeedback/kuserfeedback-1.3.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 MIT
Requires: kuserfeedback-bin = %{version}-%{release}
Requires: kuserfeedback-data = %{version}-%{release}
Requires: kuserfeedback-lib = %{version}-%{release}
Requires: kuserfeedback-license = %{version}-%{release}
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : flex
BuildRequires : kuserfeedback-dev
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev mesa-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# KUserFeedback
Framework for collecting feedback from application users via telemetry and targeted surveys.

%package bin
Summary: bin components for the kuserfeedback package.
Group: Binaries
Requires: kuserfeedback-data = %{version}-%{release}
Requires: kuserfeedback-license = %{version}-%{release}

%description bin
bin components for the kuserfeedback package.


%package data
Summary: data components for the kuserfeedback package.
Group: Data

%description data
data components for the kuserfeedback package.


%package dev
Summary: dev components for the kuserfeedback package.
Group: Development
Requires: kuserfeedback-lib = %{version}-%{release}
Requires: kuserfeedback-bin = %{version}-%{release}
Requires: kuserfeedback-data = %{version}-%{release}
Provides: kuserfeedback-devel = %{version}-%{release}
Requires: kuserfeedback = %{version}-%{release}

%description dev
dev components for the kuserfeedback package.


%package lib
Summary: lib components for the kuserfeedback package.
Group: Libraries
Requires: kuserfeedback-data = %{version}-%{release}
Requires: kuserfeedback-license = %{version}-%{release}

%description lib
lib components for the kuserfeedback package.


%package license
Summary: license components for the kuserfeedback package.
Group: Default

%description license
license components for the kuserfeedback package.


%prep
%setup -q -n kuserfeedback-1.3.0
cd %{_builddir}/kuserfeedback-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707415155
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-apx
pushd clr-build-apx
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CC=gcc-14
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf -mavx10.1 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707415155
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kuserfeedback
cp %{_builddir}/kuserfeedback-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/kuserfeedback/ed938678eaa4f37c45a62a0a3bf65b85547f0a2a || :
cp %{_builddir}/kuserfeedback-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kuserfeedback/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kuserfeedback-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kuserfeedback/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/kuserfeedback-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/kuserfeedback/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v3
pushd clr-build-apx
%make_install_va  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/UserFeedbackConsole
/V3/usr/bin/userfeedbackctl
/usr/bin/UserFeedbackConsole
/usr/bin/userfeedbackctl

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kuserfeedback-console.desktop
/usr/share/locale/ar/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ar/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/az/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/az/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/bg/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/bg/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ca/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ca/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/cs/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/cs/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/da/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/da/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/de/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/de/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/es/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/es/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/et/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/et/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/fi/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/fi/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/fr/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/fr/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/gl/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/gl/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ia/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ia/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/id/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/id/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/it/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/it/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ja/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ja/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ka/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ka/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ko/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ko/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/lt/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/lt/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/nl/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/nl/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/nn/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/pl/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/pl/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/pt/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/pt/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ro/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/ru/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/ru/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/sk/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/sk/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/sl/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/sl/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/sv/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/sv/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/tr/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/tr/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/uk/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/uk/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/userfeedbackconsole5_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/userfeedbackprovider5_qt.qm
/usr/share/metainfo/org.kde.kuserfeedback-console.appdata.xml
/usr/share/qlogging-categories5/org_kde_UserFeedback.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KUserFeedback/AbstractDataSource
/usr/include/KUserFeedback/ApplicationVersionSource
/usr/include/KUserFeedback/CompilerInfoSource
/usr/include/KUserFeedback/CpuInfoSource
/usr/include/KUserFeedback/FeedbackConfigDialog
/usr/include/KUserFeedback/FeedbackConfigUiController
/usr/include/KUserFeedback/FeedbackConfigWidget
/usr/include/KUserFeedback/LocaleInfoSource
/usr/include/KUserFeedback/NotificationPopup
/usr/include/KUserFeedback/OpenGLInfoSource
/usr/include/KUserFeedback/PlatformInfoSource
/usr/include/KUserFeedback/PropertyRatioSource
/usr/include/KUserFeedback/Provider
/usr/include/KUserFeedback/QPAInfoSource
/usr/include/KUserFeedback/QtVersionSource
/usr/include/KUserFeedback/ScreenInfoSource
/usr/include/KUserFeedback/StartCountSource
/usr/include/KUserFeedback/StyleInfoSource
/usr/include/KUserFeedback/SurveyInfo
/usr/include/KUserFeedback/UsageTimeSource
/usr/include/KUserFeedback/abstractdatasource.h
/usr/include/KUserFeedback/applicationversionsource.h
/usr/include/KUserFeedback/compilerinfosource.h
/usr/include/KUserFeedback/cpuinfosource.h
/usr/include/KUserFeedback/feedbackconfigdialog.h
/usr/include/KUserFeedback/feedbackconfiguicontroller.h
/usr/include/KUserFeedback/feedbackconfigwidget.h
/usr/include/KUserFeedback/kuserfeedback_version.h
/usr/include/KUserFeedback/kuserfeedbackcore_export.h
/usr/include/KUserFeedback/kuserfeedbackwidgets_export.h
/usr/include/KUserFeedback/localeinfosource.h
/usr/include/KUserFeedback/notificationpopup.h
/usr/include/KUserFeedback/openglinfosource.h
/usr/include/KUserFeedback/platforminfosource.h
/usr/include/KUserFeedback/propertyratiosource.h
/usr/include/KUserFeedback/provider.h
/usr/include/KUserFeedback/qpainfosource.h
/usr/include/KUserFeedback/qtversionsource.h
/usr/include/KUserFeedback/screeninfosource.h
/usr/include/KUserFeedback/startcountsource.h
/usr/include/KUserFeedback/styleinfosource.h
/usr/include/KUserFeedback/surveyinfo.h
/usr/include/KUserFeedback/usagetimesource.h
/usr/lib64/cmake/KUserFeedback/KUserFeedbackConfig.cmake
/usr/lib64/cmake/KUserFeedback/KUserFeedbackConfigVersion.cmake
/usr/lib64/cmake/KUserFeedback/KUserFeedbackTarget-relwithdebinfo.cmake
/usr/lib64/cmake/KUserFeedback/KUserFeedbackTarget.cmake
/usr/lib64/libKUserFeedbackCore.so
/usr/lib64/libKUserFeedbackWidgets.so
/usr/lib64/qt5/mkspecs/modules/qt_KUserFeedbackCore.pri
/usr/lib64/qt5/mkspecs/modules/qt_KUserFeedbackWidgets.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKUserFeedbackCore.so.1.3.0
/V3/usr/lib64/libKUserFeedbackWidgets.so.1.3.0
/V3/usr/lib64/qt5/qml/org/kde/userfeedback/libKUserFeedbackQml.so
/usr/lib64/libKUserFeedbackCore.so.1
/usr/lib64/libKUserFeedbackCore.so.1.3.0
/usr/lib64/libKUserFeedbackWidgets.so.1
/usr/lib64/libKUserFeedbackWidgets.so.1.3.0
/usr/lib64/qt5/qml/org/kde/userfeedback/libKUserFeedbackQml.so
/usr/lib64/qt5/qml/org/kde/userfeedback/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kuserfeedback/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/kuserfeedback/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kuserfeedback/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
/usr/share/package-licenses/kuserfeedback/ed938678eaa4f37c45a62a0a3bf65b85547f0a2a
